spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.103:3306/zipkin?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql

sleuth:
  enabled: true